---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.name }}-gunicorn-config"
data:
  gunicorn-config.py: |
    bind = '0.0.0.0:8000'
    workers = 1
    threads = 4
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.name }}-nginx-config"
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;
    events {
        worker_connections  1024;
    }
    
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
    
        log_format main escape=json
          '{'
            '"time_local":"$time_local",'
            '"remote_addr":"$remote_addr",'
            '"remote_user":"$remote_user",'
            '"request":"$request",'
            '"http.status_code": "$status",'
            '"body_bytes_sent":"$body_bytes_sent",'
            '"duration":$request_time,'
            '"upstream_status":"$upstream_status",'
            '"http_referrer":"$http_referer",'
            '"http_user_agent":"$http_user_agent",'
            '"http_x_forwarded_for":"$http_x_forwarded_for",'
            '"sent_http_content_type":"$sent_http_content_type",'
            '"service":"{{ .Values.name }}",'
            '"application_stage":"{{ .Values.env.APPLICATION_STAGE }}",'
            '"log_source":"nginx",'
            '"message": "$remote_addr - $remote_user [$time_local] $request $status $body_bytes_sent $request_time $upstream_status $http_referer $http_user_agent $http_x_forwarded_for"'
          '}';
        sendfile        on;
        keepalive_timeout  65;
        gzip  on;
    
        server {
            listen  80;
            server_name {{ .Values.host }}.{{ .Values.domain }};
            root /app;
            if ($http_x_forwarded_proto = "http") {
                return 301 https://$server_name$request_uri;
            }
            location / {
                proxy_pass http://localhost:8000;
                proxy_set_header Host $http_host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
                proxy_set_header X-Forwarded-Host $server_name;
            }
    
            location = /favicon.ico {
                access_log off;
                log_not_found off;
            }
        }
    }