image:
  repository: ""
  tag: latest
  pullPolicy: Always

name: ""
domain: ""
host: ""

ingressAnnotations:
  cert-manager.io/cluster-issuer: letsencrypt-prod
  acme.cert-manager.io/http01-edit-in-place: "true"

env:
  APPLICATION_STAGE: prod

container:
  port: 8000

ports:
  http:
    port: 8000
    targetPort: 8000
    nodePort: ""

service:
  type: NodePort

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}