{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  {{- if or (.Values.service.annotations) }}
  annotations:
  {{- end }}
  {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "base-service.labels" . | nindent 4 }}
  name: {{ include "base-service.name" . }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
      name: http
  selector:
    {{- include "base-service.selectorLabels" . | nindent 4 }}
{{- end }}